# Generated by Django 3.1.4 on 2021-05-16 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Gasolineras',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Precios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['precio'],
            },
        ),
        migrations.CreateModel(
            name='Tipo_Precio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tipo_Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=50)),
                ('clave', models.CharField(max_length=50)),
                ('tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gasolineras.tipo_usuario')),
            ],
            options={
                'ordering': ['usuario'],
            },
        ),
        migrations.CreateModel(
            name='Precios_Zonas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gasolineras.precios')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gasolineras.zona')),
            ],
            options={
                'ordering': ['precio'],
            },
        ),
        migrations.CreateModel(
            name='Precios_Gasolineras',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gasolinera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gasolineras.gasolineras')),
                ('precio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gasolineras.precios')),
                ('tipo_precio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gasolineras.tipo_precio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gasolineras.usuarios')),
            ],
            options={
                'ordering': ['precio'],
            },
        ),
        migrations.AddField(
            model_name='precios',
            name='tipo_precio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gasolineras.tipo_precio'),
        ),
        migrations.AddField(
            model_name='precios',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gasolineras.usuarios'),
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gasolineras.departamento')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='gasolineras',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gasolineras.municipio'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gasolineras.zona'),
        ),
    ]
