# Generated by Django 3.2.3 on 2021-05-30 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gasolineras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Gasolina',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='zona',
            options={},
        ),
        migrations.AlterField(
            model_name='precios',
            name='fecha_creacion',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='precios',
            name='tipo_gasolina',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gasolineras.tipo_gasolina'),
            preserve_default=False,
        ),
    ]
