# Generated by Django 3.0.8 on 2021-06-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasolineras', '0003_remove_precios_gasolineras_tipo_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precios',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
