# Generated by Django 3.0.8 on 2021-06-24 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gasolineras', '0005_auto_20210624_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='precios',
            old_name='id_precio',
            new_name='id',
        ),
    ]
